routes/web.php
<?php
Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'StudentController@index');
	Route::get('/home', 'StudentController@index')->name('home');

    Route::resources([
	    'students' => 'StudentController',
	    'accounts' => 'AccountController',
	]);

	Route::get('/invoice/create/{student_id}', 'InvoiceController@create')->name('invoices.create');
	Route::post('/invoice/{student_id}', 'InvoiceController@store')->name('invoices.store');
	Route::delete('/invoice/{id}', 'InvoiceController@destroy')->name('invoices.destroy');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    /**
     * Remove guarded fields
     */
    protected $guarded = [];

    /**
     * Generate NIM
     * @return string
     */
    public static function genNIM()
    {
        $lastStudent = self::orderBy('created_at', 'desc')->first();
        if (!$lastStudent) :
            $sku = 'MHSW001';
        else :
            $sku = sprintf('MHSW%03d', (int)str_replace('MHSW', '', $lastStudent->nim) + 001);
        endif;
        return $sku;
    }

    /**
     * Relation with Invoices
     */
    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Student::paginate(10);

        return view('students.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:25',
            'study' => 'required|not_in:0',
        ]);

        Student::Create([
            'nim' => Student::genNIM(),
            'name' => $request->name,
            'study' => $request->study
        ]);

        return redirect()
                ->route('students.index')
                ->with('success', 'Student has been added.'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Student::find($id);
        $invoices   = $data->invoices;

        return view('students.show', compact('data','invoices'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Student::find($id);

        return view('students.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:25',
            'study' => 'required|not_in:0',
        ]);

        $student = Student::find($id);
        $student->name = $request->name;
        $student->study = $request->study;
        $student->save();

        return redirect()
                ->route('students.index')
                ->with('success', 'Student has been updated.'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);
        $student->delete();

        return redirect()
                ->route('students.index')
                ->with('success', 'Student has been removed.'); 
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <span class="h4">Create a Student</span>
                    <a href="{{ route('students.index') }}" class="btn btn-sm btn-secondary float-right">X</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('students.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="name">{{ __('Student Name') }}</label>
                            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}"  placeholder="Student Name">
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="study">{{ __('Field of Study') }}</label>

                            <select name="study" id="study" class="custom-select {{ $errors->has('study') ? ' is-invalid' : '' }}">
                              <option value="" selected>Choose a study</option>
                              <option value="Engineering Informatics" {{ (old('study') == 'Engineering Informatics' ? "selected":"") }}>Engineering Informatics</option>
                              <option value="Computer Science" {{ (old('study') == 'Computer Science' ? "selected":"") }}>Computer Science</option>
                              <option value="Informatics Systems" {{ (old('study') == 'Informatics Systems' ? "selected":"") }}>Informatics Systems</option>
                            </select>
                            @if ($errors->has('study'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('study') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Create</button> 
                            <button type="reset" class="btn btn-secondary">Reset</button> 
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <span class="h4">Create a Student</span>
                    <a href="{{ route('students.index') }}" class="btn btn-sm btn-secondary float-right">Cancel</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('students.update', $data->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name">{{ __('NIM') }}</label>
                            <input id="name" type="text" class="form-control" value="{{ $data->nim }}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="name">{{ __('Student Name') }}</label>
                            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') ?? $data->name }}"  placeholder="Student Name">
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="study">{{ __('Field of Study') }}</label>

                            <select name="study" id="study" class="custom-select {{ $errors->has('study') ? ' is-invalid' : '' }}">
                              <option value="" selected>Choose a study</option>
                              <option value="Engineering Informatics" {{ (old('study') || $data->study == 'Engineering Informatics' ? "selected":"") }}>Engineering Informatics</option>
                              <option value="Computer Science" {{ (old('study') || $data->study == 'Computer Science' ? "selected":"") }}>Computer Science</option>
                              <option value="Informatics Systems" {{ (old('study') || $data->study == 'Informatics Systems' ? "selected":"") }}>Informatics Systems</option>
                            </select>
                            @if ($errors->has('study'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('study') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Save Changes</button> 
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="page-title mb-2">
		<span class="h4">Students List</span>
        <a href="{{ route('students.create') }}" class="btn btn-sm btn-primary float-right">Add New</a>
	</div>
	<table class="table table-bordered bg-white shadow">
    	<thead class="thead-light">
    		<tr>
    			<th>NIM</th>
    			<th>Name</th>
    			<th>Study</th>
    			<th class="text-right">Actions</th>
    		</tr>
    	</thead>
    	<tbody>
            @forelse($data as $student)
            	<tr>
            		<td>{{ $student->nim }}</td>
            		<td>{{ $student->name }}</td>
            		<td>{{ $student->study }}</td>
            		<td class="text-right">
            			<a class="btn btn-primary btn-sm" href="{{ route('students.show', $student->id) }}">View</a>

            			<a class="btn btn-secondary btn-sm" href="{{ route('students.edit', $student->id) }}">Edit</a>
            			<form class="d-inline" action="{{ route('students.destroy', $student->id) }}" method="POST">
            				@method('DELETE')
            				@csrf
            				<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this student?');">Delete</button>
						</form>
            		</td>
            	</tr>
            @empty
                <tr>
                    <td colspan="5">
                        <p class="alert alert-info">
                            Not yet data available. <a href="{{ route('students.create') }}">Add New</a>
                        </p>
                    </td>
                </tr>
            @endforelse
    	</tbody>
    </table>

    {{ $data->links() }}

</div>
@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body">
                    <h4>Student Informations</h4>
                    <table class="table table-bordered mb-0">
                        <tbody>
                            <tr>
                                <th>NIM</th>
                                <td>{{ $data->nim }}</td>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <td>{{ $data->name }}</td>
                            </tr>
                            <tr>
                                <th>Study</th>
                                <td>{{ $data->study }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <h4>Invoices List: <a class="btn btn-sm btn-primary float-right" href="{{ route('invoices.create', $data->id) }}">Create an Invoice</a> </h4>
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Number</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Created at</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                @forelse($invoices as $invoice)
                <tbody>
                    <tr>
                        <td>{{ $invoice->number }}</td>
                        <td>Rp. {{ num2rp($invoice->amount) }}</td>
                        <td>{{ ucfirst($invoice->status) }}</td>
                        <td>{{ $invoice->created_at->format('d / M / Y') }}</td>
                        <td>
                            @if($invoice->status == 'unpaid')
                            <form class="d-inline" action="{{ route('invoices.destroy', $invoice->id) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this invoice?');">Delete</button>
                            </form>
                            @else
                            <button type="submit" class="btn btn-secondary btn-sm">Print</button>
                            @endif
                        </td>
                    </tr>
                </tbody>
            @empty
                <tr>
                    <td colspan="5">
                        <p class="alert alert-info">
                            This student don't have an invoice. 
                            <a href="{{ route('invoices.create', $data->id) }}">Create invoice now</a>
                        </p>
                    </td>
                </tr>
            @endforelse
            </table>
        </div>
    </div>
</div>
@endsection